# Generated by Django 5.0.14 on 2026-05-24 17:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approval_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField(db_index=True)),
                ('changes', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('record_date', models.DateField(db_index=True)),
                ('standard_category', models.CharField(choices=[('fuel', 'Fuel Consumption'), ('electricity', 'Electricity Consumption'), ('travel', 'Business Travel')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(max_length=20)),
                ('data', models.JSONField(help_text='Normalized and standardized JSON attributes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analyst Approval'), ('APPROVED', 'Approved and Finalized'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'normalized_records',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('row_number', models.IntegerField()),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'raw_records',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing File'), ('COMPLETED', 'Completed Ingestion'), ('FAILED', 'Ingestion Failed')], db_index=True, default='PENDING', max_length=20)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], db_index=True, max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('warning', 'Warning (Review Advised)'), ('error', 'Error (Ingestion Blocked)')], db_index=True, default='warning', max_length=20)),
                ('rule_code', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'validation_issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
