# Generated by Django 5.0.14 on 2026-05-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='normalized_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ingestion.normalizedrecord'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='rawupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.rawupload'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.rawupload'),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='normalized_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='ingestion.normalizedrecord'),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='raw_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('raw_upload', 'row_number')},
        ),
    ]
